#!/bin/bash

source /etc/tinc/tinc-net.conf

ip link set $INTERFACE up
ip addr add $VPN_IP/32 dev $INTERFACE
ip route add $VPN_NET/24 dev $INTERFACE

if [[ -z ${VPN_GW:-} ]]
then
	sysctl -w net.ipv4.ip_forward=1
	# XXX: iptables -t nat -A POSTROUTING -o venet0 -j MASQUERADE
	# XXX: iptables -A INPUT -i venet0 -m state --state ESTABLISHED,RELATED -j ACCEPT
else
	ip route add $VPN_GW/32 via $DEFAULT_GW dev $DEFAULT_INTERFACE
	ip route add default via $VPN_IP dev $INTERFACE metric $VPN_METRIC
fi
